apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fbcy5epu4-go 
  janus-idp.io/tekton: fbcy5epu4-go
  backstage.io/kubernetes-id: fbcy5epu4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fbcy5epu4-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  