apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fbcy5epu4-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbcy5epu4-go 
  name: fbcy5epu4-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fbcy5epu4-go 
